export const loadingFlavourTexts = [
  "Comparing discounts across 7 galaxies…",
  "Polishing virtual shopping carts…",
  "Checking if free shipping applies…",
  "Unpacking the algorithmic tote bag…",
  "Finding the best deal in aisle 42…",
  "Untangling coupon codes…",
  "Asking customer reviews for advice…",
  "Calibrating price scanners…",
  "Rummaging through clearance racks…",
  "Filling digital shelves…",
  "Applying ‘just browsing’ mode…",
  "Balancing supply and demand scales…",
  "Shining up loyalty points…",
  "Haggling with virtual vendors…",
  "Double-checking barcode accuracy…",
  "Testing durability of shopping bags…",
  "Comparing ‘add to cart’ buttons…",
  "Refreshing flash sale timers…",
  "Scanning for hidden gems…",
  "Stocking up on patience…",
  "Trying on algorithms in the fitting room…",
  "Sharpening price tags…",
  "Asking the AI stylist for advice…",
  "Checking if it’s in stock…",
  "Restocking snack aisle…",
  "Counting imaginary inventory…",
  "Pairing socks properly…",
  "Stacking digital shelves neatly…",
  "Securing shopping cart wheels…",
  "Sorting by ‘most fabulous’…",
  "Adding gift wrap with care…",
  "Adjusting seasonal discounts…",
  "Hunting for last-minute bargains…",
  "Ironing virtual receipts…",
  "Running background checkout dance…",
  "Flipping through fashion lookbooks…",
  "Loading coupons into rocket boosters…",
  "Recycling expired deals…",
  "Testing mirror selfies…",
  "Cross-checking style with stars…",
  "Rolling out the red checkout carpet…",
  "Sharpening scissors for ribbon cutting…",
  "Polishing digital storefront windows…",
  "Counting loyalty points like treasure…",
  "Asking the cashier bot for approval…",
  "Testing shelf-stability of data…",
  "Scanning barcodes at light speed…",
  "Comparing carts per capita…",
  "Making sure sizes are true-to-fit…",
  "Applying ‘treat yourself’ mode…"
];
